<template>
    <show-page :isShowPar="true" :opacity="1" :isClickBg="true">
        <!-- 声明 -->
        <div ref="statement" class="statement-div">
            <div v-html="statementDec"></div>
        </div>
    </show-page>
</template>

<script>

export default {
    name: "main-page-bg",
    props: {
        CHENFLAF: {
            type: Boolean,
            default: true,
        },
    },
    data() {
        return {
            statementDec: "",
            statementDecList: [
                "声明：",
                "1、使用本启动器/源码即代表您同意并遵守这些条款和条件，如果您不同意，请不要使用本启动器/源码。",
                "2、源码开放，你可以拿源码去进行任意修改，但请不要用于商用，商用必究！",
                "3、本启动器/源码仅供学习和娱乐使用，不保证生成的图片的准确性、完整性、合法性或适用性。",
                "4、本启动器/源码不对生成的图片的版权、知识产权或其他权利负责，也不对生成的图片造成的任何损失或纠纷负责。",
                "5、你使用本启动器/源码生成的图片，必须遵守相关的法律法规，不得用于任何违法或不道德的目的；如果你违反了这一条款，你将自行承担所有责任和后果，与本启动器/源码无关。"
            ],
            statementDecListEn: [
                "Statement",
                "1、By using this launcher/source code, you agree to and comply with these terms and conditions. If you do not agree, please do not use this launcher/source code.",
                "2、The source code is open, you can take the source code and make any modifications, but please do not use it for commercial purposes, commercial use will be investigated!",
                "3、This launcher/source code is for learning and entertainment purposes only, and does not guarantee the accuracy, completeness, legality or applicability of the generated images.",
                "4、This launcher/source code is not responsible for the copyright, intellectual property or other rights of the generated images, nor is it responsible for any loss or dispute caused by the generated images.",
                "5、You must comply with relevant laws and regulations when using the images generated by this launcher/source code, and do not use them for any illegal or immoral purposes; if you violate this clause, you will bear all responsibility and consequences by yourself, and this launcher/source code has nothing to do with it."
            ],
        };
    },
    watch: {
        CHENFLAF() {
            this.showDec(100);
        }
    },
    mounted() {
        this.showDec(2000);
    },
    methods: {
        showDec(t) {
            this.showDecTimer && clearTimeout(this.showDecTimer);
            this.statementDec = "";
            let str = this.CHENFLAF ? this.statementDecList.join("<br>") : this.statementDecListEn.join("<br>");
            let list = str.split("");
            this.showDecTime(list, t, 0);
        },
        showDecTime(list, t, i) {
            this.showDecTimer = setTimeout(() => {
                clearTimeout(this.showDecTimer);
                let len = list.length;
                if (i < len) {
                    this.statementDec = `${this.statementDec}${list[i]}`;
                    t = this.CHENFLAF ? 60 : 20;
                    this.showDecTime(list, t, i + 1)
                }
            }, t);
        },
    },
};
</script>
<style scoped>
.statement-div {
    display: flex;
    flex-direction: column;
    text-align: left;
    position: fixed;
    padding: 10px;
    bottom: -95vh;
    left: 8%;
    width: 80%;
    height: auto;
    z-index: 990;
    border-radius: 10px;
    color: #FFFFFF;
    background: rgb(0 0 0 / 45%);
}
</style>